### ISSUE TITLE
能够直接把歌单作为播放列表

### ISSUE THREAD

**Issue by youthlin** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#11]
而不需要全选后手动添加到播放列表。

**Comment by youthlin** [comment]
原来加入播放列表后，循环方式就是‘本地音乐’栏目所选的方式。

**Comment by n374** [comment]
类似于右键 - 播放歌单 自动将当前歌单歌曲添加到播放列表？

**Comment by youthlin** [comment]
我的意思是，比如播放‘我喜欢的’这个列表，那么就【在这个列表里循环播放】，

现在是点击‘我喜欢的’列表的一首歌，那么默认它会加入‘播放列表’，但是‘我喜欢的’列表里的其他歌没有啊，所以下一首是‘播放列表’里的下一首，而不是‘我喜欢的’列表里的下一首。

**Comment by n374** [comment]
目前的操作逻辑和网易网页版一致（客户端用得少不清楚）
对于歌单里的歌曲，可以：
点击网页版歌曲前的播放按钮，将歌曲添加到播放列表，对应着插件双击添加并播放；
或者点击网页版歌单名下方的播放按钮，将所有歌曲添加到播放列表并播放，这个目前插件需要手动Ctrl-A全选并播放，如果觉得这步不方便可以加一个右键菜单，直接将当前歌曲添加并播放。

如果将双击绑定到添加并播放当前歌单，会与常用的操作方式冲突。

如果有更方便更直观的方式，欢迎提出。

**Comment by youthlin** [comment]
特意去网页版看了下，原来有个播放整个歌单的按钮
单击一首歌播放，的确是只加入他自己到播放列表

![music1](https://cloud.githubusercontent.com/assets/6056413/9789879/3a1bf2f0-5805-11e5-87ad-9cdbcb48f4a6.png)

不过有个播放歌单按钮，会把整个歌单自动加入播放列表

![music2](https://cloud.githubusercontent.com/assets/6056413/9789887/40b4f684-5805-11e5-93c1-3a92b1c8020e.png)

**Comment by n374** [comment]
是的 所以如果有需要 可以加两个右键菜单选项“添加歌单到播放列表”，“播放歌单”（将歌单里的歌曲添加到播放列表并播放）。

按钮就不添加了，本来空间就小，能放菜单的都放菜单。
