### ISSUE TITLE
Deepin下的通知不能显示专辑信息

### ISSUE THREAD

**Issue by youthlin** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#12]
右上角的通知，歌曲名称显示正常，专辑名显示的是貌似是json数据

![neteasemusic](https://cloud.githubusercontent.com/assets/6056413/9752727/3e8d0dc6-56e6-11e5-8e44-5fc6fcae49b8.png)

**Comment by n374** [comment]
99b3802609eb016c69fdad9b5fcc8af64cdc7903
现在在Ubuntu下测试没问题
没有Deepin环境
