### ISSUE TITLE
Incorrect metadata

### ISSUE THREAD

**Issue by ghost** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#13]
![screenshot from 2015-09-11 14 10 05](https://cloud.githubusercontent.com/assets/8991941/9822540/fd986b1c-588e-11e5-84a5-cdd1b5977ea6.png)

Just as the picture shows.
Thanks!

**Comment by n374** [comment]
This issue have already been fixed in #12  99b3802609eb016c69fdad9b5fcc8af64cdc7903
Update the code, reinstall the plugin, empty your playling list. Let me know if still any problem.

**Comment by ghost** [comment]
It works perfectly now! Thanks!
