### ISSUE TITLE
请求添加下载功能.

### ISSUE THREAD

**Issue by ssfdust** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#14]
如果咱有空会写个PR(毕竟很多东西都有了 :)

PS:
dmusic-plugin-NeteaseCloudMusic/neteasecloudmusic/netease_music_view.py
中的265行,有个手误
        munu_items = [(None, item.title, add_song_to_list, item, songs, sids)
应该是menu_items...

**Comment by n374** [comment]
下载这个问题考虑过。
这个插件的目的是将网页版上的功能实现，而下载这个功能目前只在客户端上有，且不常用（个人感觉）
，同时可能因为像320KB加密算法那样太直接而导致插件被官方要求删除，所以还是不加了。

如果有这个需求，可以写个脚本单独实现。

**Comment by ssfdust** [comment]
好吧，Closed
