### ISSUE TITLE
内存占用随着播放增加

### ISSUE THREAD

**Issue by SnDream** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#15]
在Debian8下根据官方包所需的依赖，挨个安装上了
python-deepin-utils_0.1.99-1_amd64.deb
deepin-ui_1.0.4+r2-g8d75806_all.deb
python-deepin-gsettings_0.2_amd64.deb
deepin-music_2.3.0-4_all.deb
这几个包，正常运行后，装上了插件。
但是用插件的时候，使用得久了，内存也随之明显增加。
启动的时候内存占用大约是220M，听一个下午能涨到750M。
似乎本地播放不会导致内存明显增加。

我也不确定是深度自己的问题还是插件的问题，有没有检测出问题的合适方法？谢谢。

**Comment by n374** [comment]
我搜索了下，python-gtk2可能会导致内存泄漏，安装Deepin打过补丁的包试试。
[32位](http://packages.linuxdeepin.com/deepin/pool/main/p/pygtk/python-gtk2_2.24.0-3deepin2_i386.deb)
[64位](http://packages.linuxdeepin.com/deepin/pool/main/p/pygtk/python-gtk2_2.24.0-3deepin2_amd64.deb)

**Comment by SnDream** [comment]
谢谢，我已经安装上相关包继续测试。
顺便给一些控制台输出的与python以及dtk有关的错误信息，看看有没有帮助。

---

/usr/lib/python2.7/dist-packages/dtk/ui/utils.py:396: PangoWarning: pango_layout_set_markup_with_accel: 第 1 行出错：实体没有以分号结束。很可能您使用了 & 字符而又不是一个实体 - 将这个 & 变为 &amp;
  layout.set_markup(text)

---

/usr/lib/python2.7/dist-packages/dtk/ui/tooltip.py:280: Warning: Source ID 10020 was not found when attempting to remove it
  gobject.source_remove(TooltipInfo.show_id)
/usr/lib/python2.7/dist-packages/dtk/ui/animation.py:176: Warning: Source ID 10169 was not found when attempting to remove it
  gobject.source_remove(self.animation_id)
/usr/lib/python2.7/dist-packages/dtk/ui/animation.py:178: Warning: Source ID 10070 was not found when attempting to remove it
  gobject.source_remove(self.start_id)

**Comment by n374** [comment]
utils.py出错经常能见到。
下面那个没太注意，看提示都是Deepin自己写的dtk的问题，不清楚会有什么后果。

**Comment by SnDream** [comment]
实测有效，就是比较奇怪，python-gtk2为何会出现内存泄漏，在Debian8源内安装包还无法解决这个问题的情况下我还是锁定python-gtk2的版本吧。
非常感谢！

**Comment by n374** [comment]
据说是Bug，Deepin打上了补丁，可能还没有合并到上游。
这至少是2013年的消息了，现在还没有解决么？
一想到你用的是Debina好像就明白了。

**Comment by SnDream** [comment]
第一次感觉Debian稳定过了头，到了稳定高于BUG的地步。
