### ISSUE TITLE
Could you please add proxy functionality to the plugin?

### ISSUE THREAD

**Issue by ghost** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#18]
It seems that 163 blocked oversea users recently. Thus this could be a good feature~

**Comment by n374** [comment]
NetEase blocked the access to the mp3 url, thus plugin get the information but player can't play it.
You can [set proxy](https://wiki.archlinux.org/index.php/Proxy_settings), then run deepin-music-player in the same terminal, it should works.

**Comment by ghost** [comment]
You mean the cache process of the music is done in the music player other than the plugin, don't you?

**Comment by n374** [comment]
Yes.
Plugin works fine but player can't cache music, add proxy to plugin only won't change anything.
Set proxy and run commmand "deepin-music-player" in the same terminal, both player and plugin will connect to NetEase through the proxy.

**Comment by ghost** [comment]
I see. Thank you all the same!
