### ISSUE TITLE
openSUSE 13.2 下无法安装插件

### ISSUE THREAD

**Issue by xhmelon** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#19]
其实我已经解决了这个问题，发这个 issue 是为了给可能遇到相同问题的同学帮助。
今天在 openSUSE 13.2 下安装此插件失败，即使是 sudo 后也不行。问题解决方法如下：
git clone 插件到本地，然后将 neteasecloudmusic 文件夹复制到 /usr/share/deepin-music/plugins 下即可。

```
git clone https://github.com/wu-nerd/dmusic-plugin-NeteaseCloudMusic.git
cd dmusic-plugin-NeteaseCloudMusic
# cp neteasecloudmusic -r /usr/share/deepin-music/plugins
```

**Comment by n374** [comment]
想问下openSUSE 13.2下默认Python版本及你目前环境下的默认版本，因为如果默认Python3的话会出现类似情况。
