### ISSUE TITLE
不清楚是否可以实现用第三方的应用进行登录

### ISSUE THREAD

**Issue by rccoder** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#2]
我是用**微博**进行登录的，需要去官网绑定手机后才可以进行登录，不知否可以实现在deepin-music界面进行第三方登录

**Comment by n374** [comment]
已添加新浪微博账号及二维码登录功能
e308759ff340c800ee2ea989af334a9e7265fbc9

网易云音乐即将不支持腾讯微博登录，因此就不添加了
