### ISSUE TITLE
ubuntu kylin 15.10下无法播放

### ISSUE THREAD

**Issue by Nanporo** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#21]
我都是照着安装步骤来装插件的，登入和搜尋可以用

但就是不能播...

深度音乐是2.0版，是从深度那边找来Deb包安装

ukylin和ubuntu应该不会差太多…？

**Comment by n374** [comment]
先打开本地音乐测试能否正常播放
如果可以，尝试在终端打开deepin-music-player，看会有什么错误提示

**Comment by Nanporo** [comment]
> ~$ deepin-music-player
> INFO     Loading settings...
> INFO     Loading application theme...
> INFO     Loading MediaDB...
> INFO     Initialize Gui...
> 
> *\* (deepin-music-player:29389): WARNING **: Binding '<Alt>P' failed!
> 
> *\* (deepin-music-player:29389): WARNING **: Binding '<Alt>W' failed!
> /usr/lib/python2.7/dist-packages/dtk/ui/utils.py:396: PangoWarning: pango_layout_set_markup_with_accel: 第 1 列发生错误：实体的结束部分不是分号；很可能您想使用 & 字元但未将它变为实体─请将 & 转换为 &amp;
>   layout.set_markup(text)
> INFO     MMKeys mode: gnome
> /usr/lib/python2.7/dist-packages/dtk/ui/utils.py:396: PangoWarning: pango_layout_set_markup_with_accel: Unknown tag 'unknown' on line 1 char 18
>   layout.set_markup(text)
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> ERROR    Unable to append (None,) to message with signature v: <type 'exceptions.TypeError'>: Don't know which D-Bus type to use to encode type "NoneType"
> WARNING  stream is already unlinked.  huh? "http://mr7.doub...fm/song/p1452895_128k.mp4"
> /usr/share/deepin-music/src/widget/song_view.py:642: Warning: Source ID 486 was not found when attempting to remove it
>   gobject.source_remove(self.notify_timeout_id)
> <pr> >>> Finish missions.
> <pr> >>> Wait new missions.
> <pr> >>> Finish missions.
> <pr> >>> Wait new missions.
> /usr/share/deepin-music/src/widget/song_view.py:642: Warning: Source ID 556 was not found when attempting to remove it
>   gobject.source_remove(self.notify_timeout_id)
> WARNING  stream is already unlinked.  huh? "file:///home/ro... Planning - Stargazer.mp3"

前面有捷径键问题（不过这与无法播放无关）

**Comment by Nanporo** [comment]
电台和本地音乐可以正常播放，广播不行

**Comment by n374** [comment]
广播？
什么广播？

**Comment by Nanporo** [comment]
深度音乐可以播放网络广播，电台很多

他是个内置插件，可以开启

**Comment by n374** [comment]
那么现在的情况是：
本地音乐和内置的网络广播、豆瓣电台可以播放，这个插件无法播放是吧？

那么你现在是在国内还是国外？网页版能正常播放么？

**Comment by Nanporo** [comment]
嗯对，现在情况是那样
人在台湾，网页版可以使用 没什么问题

**Comment by n374** [comment]
那么麻烦重新贴下终端输出吧，只在这个插件内播放音乐，我看看有什么错误出现。

**Comment by Nanporo** [comment]
> INFO     Loading settings...
> INFO     Loading application theme...
> INFO     Loading MediaDB...
> INFO     Initialize Gui...
> 
> *\* (deepin-music-player:32460): WARNING **: Binding '<Alt>P' failed!
> 
> *\* (deepin-music-player:32460): WARNING **: Binding '<Alt>W' failed!
> /usr/lib/python2.7/dist-packages/dtk/ui/utils.py:396: PangoWarning: pango_layout_set_markup_with_accel: 第 1 列發生錯誤：實體的結束部分不是分號；很可能您想使用 & 字元但未將它變為實體 ─ 請將 & 轉換為 &amp;
>   layout.set_markup(text)
> INFO     MMKeys mode: gnome
> /usr/lib/python2.7/dist-packages/dtk/ui/utils.py:396: PangoWarning: pango_layout_set_markup_with_accel: Unknown tag 'unknown' on line 1 char 18
>   layout.set_markup(text)
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> INFO     Starting new HTTP connection (1): music.163.com
> ERROR    Unable to append (None,) to message with signature v: <type 'exceptions.TypeError'>: Don't know which D-Bus type to use to encode type "NoneType"

嗯...似乎一样

**Comment by Nanporo** [comment]
找到了~，可能是IP问题 网页版有时会提示地区问题 VPN过去后就解決了
然後你的作品真的很好~ 谢谢！

**Comment by n374** [comment]
如果你有其他代理方式如socks代理或HTTP代理，可以配合proxychains使用。
这样不会像VPN这种全局代理那样影响其他程序的网络传输。
