### ISSUE TITLE
fedora 23下无法登陆

### ISSUE THREAD

**Issue by MichaelVipub** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#23]
命令行下启动日志如下：
[michael@localhost ~]$ deepin-music-player 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO     Loading settings...
INFO     Loading application theme...
INFO     Loading MediaDB...
INFO     Initialize Gui...
INFO     MMKeys mode: gnome
get uid failed
Vector smash protection is enabled.
cellphone login
INFO     Starting new HTTPS connection (1): music.163.com
login failed

**Comment by n374** [comment]
我在Ubuntu 12.04环境下测试，手机登陆正常，请确定输入的信息正确无误。
同时，提示中的

```
Vector smash protection is enabled.
```

是如何出现的，播放器和插件中好像都没有类似代码。

**Comment by MichaelVipub** [comment]
问题已经得到了解决。

问题原因是:
深度音乐播放器自带了插件。安装路径为/usr/share/deepin-music-player/plugins/neteasecloudmusic .
这个插件里的代码比较旧了。
删除这个代码，并重新安装就可以正常了获取歌单等信息了。
但是播放没有声音，不过这个是由于全局代理影响的，去掉代理以后也好了。

抱歉没有仔细看你的说明。

**Comment by n374** [comment]
那么请问下你的播放器是在哪/如何安装的呢？
推测使用的是第三方打的包。
如果是这样的话那么应该通知打包者进行更新，以免给其他人带来不必要的麻烦。

至于代理问题，根据我的测试和其他人的反馈（#21），当以非大陆IP访问时，会因为无法下载音频文件而无法播放，也就是进度条会一直卡在00:00处。
不知道你所说的没有声音具体是什么样的情况：国内、国外代理？进度条是否正常？在同样的情况下网页版是否正常？

**Comment by MichaelVipub** [comment]
这个是国内的fedora源fuzg深度音乐打包的。
我会尝试跟他们沟通，让他们确认下问题。

用了lantern代理，会自动设置全局代理。
我的情况确实是一直在00:00处，但是播放的按钮已经显示为播放状态了。
所以我描述为了没有声音。
