### ISSUE TITLE
歌单名字中带&的显示不出来

### ISSUE THREAD

**Issue by LER0ever** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#26]
如图，两个显示不出来的分别是"雷亚轻音乐Cytus & Deemo"和“玩游戏 & 抄作业必备...”
![screenshot_20160507_135558](https://cloud.githubusercontent.com/assets/10568668/15090493/1e475f42-145c-11e6-9db7-eb71c081df2b.png)
![screenshot_20160507_135618](https://cloud.githubusercontent.com/assets/10568668/15090474/8b0003ec-145b-11e6-9948-8b1e9d04e2aa.png)

**Comment by n374** [comment]
应该已经把因转义问题导致的BUG解决了。
如果还有未发现的，欢迎提出。

同时问一句，你是如何调节播放器的大小的？
从图中看，左侧显示歌单的VBox明显比默认情况大很多。

**Comment by LER0ever** [comment]
### 恩谢谢试了下&可以显示了。

那个PLAYLIST_WIDTH我当时还想到这提个issue的，因为歌单名字都显示不全。
然后看了下插件好像改不了大小所以自己改了。。。
大概是在播放器的constant.py:`/usr/share/deepin-music/src/constant.py`
我调的大小：

```
FULL_DEFAULT_WIDTH = 886
FULL_DEFAULT_HEIGHT = 625
SIMPLE_DEFAULT_WIDTH = 450#322
SIMPLE_DEFAULT_HEIGHT = 625
HIDE_PLAYLIST_WIDTH = 260#210
LIST_WIDTH = 440#312
CATEGROYLIST_WIDTH = 180#104
PLAYLIST_WIDTH = 198
```

注释#后面的是原大小
