### ISSUE TITLE
关于API

### ISSUE THREAD

**Issue by Hadesonly** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#28]
请问下这个API还有用么？

**Comment by n374** [comment]
基本功能都能正常使用

**Comment by Hadesonly** [comment]
包括登录什么的么？只要包含那个py文件然后使用里面函数就可以？

**Comment by n374** [comment]
是的。
原理可以参考https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%99%BB%E5%BD%95API%E5%88%86%E6%9E%90

实现代码在netease_api.py中

**Comment by yosef-gao** [comment]
如果用户歌单的歌曲数超过1000怎么办？

**Comment by n374** [comment]
@yosef-gao 
目前的处理方式是只显示前1000个，正常的逻辑是分页显示。
插件在重写中，新的版本会处理分页问题。

**Comment by dpluy** [comment]
@wu-nerd 时间来到这里，我也不能登录 是不是已经失效了

**Comment by n374** [comment]
@dpluy 
503701ce6c2c4d94f1fcd40a158c7a0077861793 
登录接口的返回值有变化，无法获取用户ID，导致登录异常，已修复
