### ISSUE TITLE
请添加 320Kbps 音频支持

### ISSUE THREAD

**Issue by legendtang** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#5]
https://github.com/darknessomi/musicbox/blob/master/NEMbox/api.py

建议看一下这位修改版的 encrypted_id 实现，原作者好像去掉了

**Comment by n374** [comment]
很多被要求删除的repo都用到这个加密算法
如：https://www.v2ex.com/t/131959  和  https://www.v2ex.com/t/123375

为了保证项目长久存活，这个加密算法我不会加入
但我会对相关代码进行调整，需要320K请自行实现
320K加密算法：
https://github.com/yanunon/NeteaseCloudMusic/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90API%E5%88%86%E6%9E%90#5-%E4%B8%8B%E8%BD%BD%E9%9F%B3%E4%B9%90%E6%96%87%E4%BB%B6

**Comment by legendtang** [comment]
支持。按你说的把代码进一步模块化吧，这样调用加密方法比较方便

**Comment by n374** [comment]
已失效

~~0bd020bd602b362d097b147ff4ae39f4a6d7d76d~~

~~在播放歌曲时，neteasecloudmusic/netease_music_browser.py中的get_better_quality_music函数
会尝试调用neteasecloudmusic文件夹下的encrypted.py文件中的encrypted_id(id)函数，
获取320K码率的URL，失败则依次尝试160K/96K码率~~

~~要播放高码率音乐，只需要手动在neteasecloudmusic文件夹下新建encrypted.py，包含encrypted_id(id)函数~~
~~具体代码可以参照https://github.com/yanunon/NeteaseCloudMusic/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90API%E5%88%86%E6%9E%90#5-%E4%B8%8B%E8%BD%BD%E9%9F%B3%E4%B9%90%E6%96%87%E4%BB%B6~~

**Comment by legendtang** [comment]
Thanks!

**Comment by wangzk** [comment]
Thanks!

**Comment by mawanglin** [comment]
Thanks

**Comment by n374** [comment]
该算法已经失效，会导致无法播放，删除即可
