### ISSUE TITLE
希望增加今日推荐的歌曲列表播放

### ISSUE THREAD

**Issue by ghost** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#9]
这个功能还蛮常用的。

等我有空也可以自己写了提交。

**Comment by n374** [comment]
每日歌曲推荐这个功能我一直打算加进去的 
因为实习 新功能的增加及现有问题的修复（比如搜索结果的异步操作）暂时往后推
欢迎Pull Requests

如果将”每日歌曲推荐“添加到左侧category_list部分 则需要修改多处内容 实现复杂
因此推荐添加到右侧的Browser部分 与“歌曲”、”歌单“一样出现在下拉选项中
这样直接在下方展示推荐歌曲 可以像搜索结果一样 选中 播放、添加到播放列表 实现简单

如果有其他不错实现方式 欢迎讨论

**Comment by ghost** [comment]
Gotcha~ 我找时间试试！

**Comment by ghost** [comment]
已经pull request，我测试没有问题。请检查一下。
